### ISSUE TITLE
Won't download anything. I get 

### ISSUE THREAD

**Issue by notKarb** [prof79/fansly-downloader-ng#100]
I get this message at the end: 

 [31]ERROR | 00:37 || Failed Messages download. Response code: 400
{"success":false,"error":{"code":99,"details":"missing groupId"}}

This is what my log file says:
[ Info ] [2024-10-26 | 00:36]: 
╔═
  GRAND TOTAL DOWNLOAD SUMMARY
  Finished downloading media for 1 creators!
  Total timeline media: 744 pictures & 13 videos (= 757 items)
  Total message media: 0
  Total media (timeline & messages): 757
  Downloaded media: 0 pictures & 0 videos (= 0 items)
  Duplicates skipped: 0
  Missing items: 757 (this may indicate a problem)
  Make sure you are following and subscribed to all creators.
                                                                          ═╝
[ Info ] [2024-10-26 | 00:37]: Reading config.ini file ...
[ Info ] [2024-10-26 | 00:37]: Name validation for @hisoneko successful!
[ WARNING ] [2024-10-26 | 00:37]: !!! FANSLY MAY BAN YOU FOR USING THIS SOFTWARE, BE WARNED !!!
[ WARNING ] [2024-10-26 | 00:37]: Web retrieval of check key failed!
[ WARNING ] [2024-10-26 | 00:37]: Make sure, checking the main.js sources of the Fansly homepage, 
                    that the expression assigend to `this.checkKey_` evaluates 
                    to this text: `qybZy9-fyszis-bybxyf`
[ Info ] [2024-10-26 | 00:37]: Acknowledging custom basis download directory: 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7'
[ Info ] [2024-10-26 | 00:37]: The current download mode is set to 'Messages'.
[ Info ] [2024-10-26 | 00:37]: Token: NjU1MzEwMjg2MDYzOTM1NjA4OjE6MjpmODIwMTA0ZTU1MWVjOWJiMWFkMmZhYTJhYTBmZGY
[ Info ] [2024-10-26 | 00:37]: Check Key: qybZy9-fyszis-bybxyf
[ Info ] [2024-10-26 | 00:37]: Device ID: 706341606952804352 (2024-10-26 00:35:22.394000)
[ Info ] [2024-10-26 | 00:37]: Session ID: 655310286063935608
[ Info ] [2024-10-26 | 00:37]: Due to important memory usage and video format bugfixes, existing media items 
                 need to be re-hashed (`_hash_`/`_hash1_` to `_hash2_`).
                 Affected files will automatically be renamed in the background.
[ Info ] [2024-10-26 | 00:37]: Deduplication is automatically enabled for:
                 C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly
[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Messages\Pictures\2024-08-01_at_05-42_id_675253589634981888.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Messages\Pictures\2024-08-01_at_05-42_id_675253599017644033.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Messages\Pictures\2024-08-01_at_06-44_id_675269105426636801.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Timeline\Pictures\2023-06-23_at_23-36_preview_id_528756822648037376.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Timeline\Pictures\2024-01-18_at_18-45_id_604437557391929344.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 276, in phash
  File "scipy\__init__.py", line 147, in __getattr__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Timeline\Pictures\2024-07-19_at_19-41_id_670753746891841536.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 276, in phash
  File "scipy\__init__.py", line 147, in __getattr__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Timeline\Pictures\2024-08-12_at_21-13_id_679474176653799424.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 276, in phash
  File "scipy\__init__.py", line 147, in __getattr__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Timeline\Pictures\2024-10-24_at_02-56_id_705652267776225280.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 276, in phash
  File "scipy\__init__.py", line 147, in __getattr__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Timeline\Pictures\2024-04-27_at_03-45_id_640434773499588609.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 276, in phash
  File "scipy\__init__.py", line 147, in __getattr__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

[ [15]ERROR ] [2024-10-26 | 00:37]: 
Error processing image 'C:\Users\TheFr\Desktop\Programs\Fansly_Downloader_NG-Windows-v0.9.7\hisoneko_fansly\Timeline\Pictures\2024-07-27_at_02-58_id_673400270880776192.jpeg': Traceback (most recent call last):
  File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 276, in phash
  File "scipy\__init__.py", line 147, in __getattr__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>

**Comment by notKarb** [comment]
I am very bad with this kind of stuff so if you can help me please write it very simply so I can understand haha c:

**Comment by palmerbomber1** [comment]
One error you will get using the windows exe `ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'` is because the special ufuncs is missing from the packaged exe, for me it was not an issue for downloading images except that it added an unnecessary pause after every image. If you can use the python module this ends up not happening.

The error line `[ WARNING ] [2024-10-26 | 00:37]: Web retrieval of check key failed!` appears to indicate that there is an issue with your check key and its not able to download anything because it might not be able to spoof access to the content. Copy and paste this at the bottom of your config file, replacing the first line after [Logic} 
`check_key_pattern = this\.checkKey_\s*=(\s*(\+?\[[^\]]+\]|\.[a-z]+\([^\)]*\)|\+?\"[^\"]*\")+\s*)+(?=,)`
and I believe this will resolve the check key issue

**Comment by notKarb** [comment]
python is so alien to me I have tried to use it and it is way too confusing for me so unless I can find a tutorial or something I don't think that will happen. I tried adding what you typed to the bottom of my config file after the Logic line but still nothing sadly

**Comment by palmerbomber1** [comment]
Nothing downloaded still? Did it at least succeed at guessing the check key? It should say `Config | 19:40 || Check key guessed from Fansly homepage: **** ` instead of `[ WARNING ] [2024-10-26 | 00:37]: Web retrieval of check key failed!`

**Comment by notKarb** [comment]
it failed at guessing the check key

**Comment by palmerbomber1** [comment]
I dont really know then. Ive been using this for about a week now, the first few days took me a bit to work out most the bugs for it to function for me.

For the python module, I followed a guide from the currently deleted issue 80 that was archived [here](http://web.archive.org/web/20241001085407/https://github.com/prof79/fansly-downloader-ng/issues/80) written by recoiler.
