### ISSUE TITLE
Problem with downloading - multiple errors?

### ISSUE THREAD

**Issue by kendrakirai** [prof79/fansly-downloader-ng#104]
First was 
```
 [31]ERROR | 03:08 || Failed Messages download. Response code: 400
{"success":false,"error":{"code":99,"details":"missing groupId"}}
```
then came 
```
 [43]ERROR | 03:09 || Unexpected error during Timeline download:
Traceback (most recent call last):
  File "download\common.py", line 151, in process_download_accessible_media
  File "download\media.py", line 202, in download_media
  File "fileio\dedupe.py", line 74, in dedupe_media_file
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'
```

and here's more after it working a little bit 

```
 [36]ERROR | 03:34 || Unexpected error during Timeline download:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 464, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 843, in urlopen
  File "urllib3\util\retry.py", line 474, in increment
  File "urllib3\util\util.py", line 38, in reraise
  File "urllib3\connectionpool.py", line 789, in urlopen
  File "urllib3\connectionpool.py", line 536, in _make_request
  File "urllib3\connection.py", line 464, in getresponse
  File "http\client.py", line 1395, in getresponse
  File "http\client.py", line 325, in begin
  File "http\client.py", line 294, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download\timeline.py", line 49, in download_timeline
  File "api\fansly.py", line 263, in get_timeline
  File "api\fansly.py", line 188, in get_with_ngsw
  File "api\fansly.py", line 153, in cors_options_request
  File "requests\sessions.py", line 613, in options
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 501, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

Also, I can't figure out how to get main.js's check key

**Comment by FloopFlop53** [comment]
I have the same problem i thought i was just doing something wrong. it used to work for me.

**Comment by superfan12345** [comment]
i was getting this and changed the download mode from normal to timeline and it worked
