### ISSUE TITLE
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs' [43]ERROR | 18:42 || Unexpected error during Single download:

### ISSUE THREAD

**Issue by ONAJETMO** [prof79/fansly-downloader-ng#106]
## Bug Description
Every time I try to download Timeline, Normal, Single, etc. It gives me a error  [15]ERROR | 18:42 || Error processing image followed by:
File "fileio\fnmanip.py", line 124, in add_hash_to_image
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 276, in phash
  File "scipy\__init__.py", line 147, in __getattr__
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

## Expected behavior
download images videos etc

## Actual behavior
Errors out and only downloads one file

[ [43]ERROR ] [2024-11-12 | 18:42]: Unexpected error during Single download: 
Traceback (most recent call last):
  File "download\common.py", line 151, in process_download_accessible_media
  File "download\media.py", line 202, in download_media
  File "fileio\dedupe.py", line 74, in dedupe_media_file
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

## Environment Information
 - Operating System: Windows
 - Fansly Downloader Version: 0.9.9
 - Fansly Downloader Type: Executable
 - Specific creators name: lolitababy2k

## User Research

I have done the following:
- [x ] Looked through [old GitHub issues](https://github.com/prof79/fansly-downloader-ng/issues?&q=is%3Aissue)
- [ x] Read the [config.ini options](https://github.com/prof79/fansly-downloader-ng/wiki/Fansly-Downloader-NG-Settings#explanation-of-configini)
- [x ] Searched the Web (like [DuckDuckGo](https://duckduckgo.com))

**Comment by JajajTec** [comment]
After a lot of digging and failing to get the python version running for 6h because of that darn plyvel-ci i finally found a solution to this problem.
The creator of this programm forgot to add a dependency in the exe, resulting in inconsistant behavior
The solution: use the win ver 0.9.7! There the dependency is still in there!
Hope i could help you and others!

**Comment by Charicyukidaru** [comment]
> 經過大量挖掘，由於那個的 plyvel-ci 而無法讓 python 版本運行 6 小時，我終於找到了解決這個問題的方法。這個程式的建立者忘記在 exe 中添加依賴項，導致行為不一致 解決方案：使用 win ver 0.9.7！那裡的依賴關係仍然存在！希望我能説明你和其他人！

I really wish I had seen your reply before spending 3 hours researching this with ChatGPT...
