### ISSUE TITLE
Unexpected error during Timeline download

### ISSUE THREAD

**Issue by deadbeatdandylyon** [prof79/fansly-downloader-ng#111]
I attempted to run a scrape of a profile today, I have verified the checkkey is correct and the user agent as well as the Auth Token, I am running this through python

Not sure what's going on or how to resolve? 

` Info | 17:39 || Downloading video '2024-10-15_at_02-38_id_702291346014089217.m3u8'
 [43]ERROR | 17:39 || Unexpected error during Timeline download:
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1428, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1428, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\common.py", line 151, in process_download_accessible_media
    download_media(config, state, accessible_media)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\media.py", line 149, in download_media
    file_save_path = download_m3u8(
        config,
        m3u8_url=media_item.download_url,
        save_path=file_save_path
    )
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\m3u8.py", line 187, in download_m3u8
    list(
    ~~~~^
        progress.track(
        ^^^^^^^^^^^^^^^
    ...<2 lines>...
        )
        ^
    )
    ^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\rich\progress.py", line 1209, in track
    for value in sequence:
                 ^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ~~~~~~~~~~^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\m3u8.py", line 150, in download_ts
    with config.get_api().get_with_ngsw(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                url=segment_uri,
                ^^^^^^^^^^^^^^^^
    ...<2 lines>...
                add_fansly_headers=False,
                ^^^^^^^^^^^^^^^^^^^^^^^^^
            ) as segment_response:
            ^
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\api\fansly.py", line 188, in get_with_ngsw
    self.cors_options_request(url)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\api\fansly.py", line 153, in cors_options_request
    self.http_session.options(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        url=url,
        ^^^^^^^^
        headers=headers,
        ^^^^^^^^^^^^^^^^
        cookies=None,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 613, in options
    return self.request("OPTIONS", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`

**Comment by deadbeatdandylyon** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 1428, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\http\client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\common.py", line 151, in process_download_accessible_media
    download_media(config, state, accessible_media)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\media.py", line 149, in download_media
    file_save_path = download_m3u8(
        config,
        m3u8_url=media_item.download_url,
        save_path=file_save_path
    )
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\m3u8.py", line 187, in download_m3u8
    list(
    ~~~~^
        progress.track(
        ^^^^^^^^^^^^^^^
    ...<2 lines>...
        )
        ^
    )
    ^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\rich\progress.py", line 1209, in track
    for value in sequence:
                 ^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ~~~~~~~~~~^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\download\m3u8.py", line 150, in download_ts
    with config.get_api().get_with_ngsw(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                url=segment_uri,
                ^^^^^^^^^^^^^^^^
    ...<2 lines>...
                add_fansly_headers=False,
                ^^^^^^^^^^^^^^^^^^^^^^^^^
            ) as segment_response:
            ^
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\api\fansly.py", line 188, in get_with_ngsw
    self.cors_options_request(url)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\<user>\Downloads\Compressed\fansly-downloader-ng-main_2\fansly-downloader-ng-main\api\fansly.py", line 153, in cors_options_request
    self.http_session.options(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        url=url,
        ^^^^^^^^
        headers=headers,
        ^^^^^^^^^^^^^^^^
        cookies=None,
        ^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 613, in options
    return self.request("OPTIONS", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

**Comment by deadbeatdandylyon** [comment]
Some facts

I am using Google Chrome, 
No VPN
Running as "Normal" Scrape
Running the python script

This only happened a few times

**Comment by akhepcat** [comment]
This error is popping up more and more:
WARNING | 14:51 || Web retrieval of check key failed!


I don't have any cached versions of main.js,  but I do see this:

this.checkKey_ = ["fySzis", "oybZy8"].reverse().join("-") + "-bubayf",

followed by:

                i.push("necvac"),
                i.push("govry3"),
                i.push("tybkYz"),
                this.checkKey_ = i.join("-")
            }


which seems to overwrite checkKey to:  'necvac-govry3-tybkYz'

**Comment by akhepcat** [comment]
Manually setting the config.ini checkkey  to what's given, and disabling the regex parsing results in this:

Info | 15:11 || Executing Timeline functionality. Anticipate remarkable outcomes!

 Info | 15:11 || Inspecting most recent Timeline cursor ... [CID: 285324679810392064]
 [42]ERROR | 15:11 || Unexpected error parsing Timeline content;
Traceback (most recent call last):
  File "fansly-downloader-ng/download/common.py", line 120, in process_download_accessible_media
    media_items += [parse_media_info(state, media_info, post_id)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fansly-downloader-ng/media/media.py", line 157, in parse_media_info
    if 'variants' in media_info['preview']:
                     ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'preview'


(although, to be fair, i was receiving the same types of errors with the original config as well.)

**Comment by palmerbomber1** [comment]
The program will rewrite the 'username=' 'check_key=' and '[Cache]' ; username is usually alphabetized and removes the @ symbol if it was added. For me to fix it not guessing the check key was to replace the first line under '[Logic]' with `check_key_pattern = this\.checkKey_\s*=(\s*(\+?\[[^\]]+\]|\.[a-z]+\([^\)]*\)|\+?\"[^\"]*\")+\s*)+(?=,)`

I also applied some suggestions from a deleted post thats found on the wayback machine, I dont know if just one or all changes are needed to make the errors go away. [Post 80](http://web.archive.org/web/20241001085407/https://github.com/prof79/fansly-downloader-ng/issues/80)

Edit: i copied from the wrong config file, corrected that error

**Comment by akhepcat** [comment]
> The program will rewrite the 'username=' 'check_key=' and '[Cache]' ; username is usually alphabetized and removes the @ symbol if it was added. For me to fix it not guessing the check key was to replace the first line under '[Logic]' with `check_key_pattern = this\.checkKey_\s*=(\s*(\+?\[[^\]]+\]|\.[a-z]+\([^\)]*\)|\+?\"[^\"]*\")+\s*)+(?=,)`

That solves a lot of it!

there's a couple of additional changes in media/media.py  starting at line 157 (local line)   where it's trying to look for variants of the media content.  Adding some validation that 'preview' and 'variants'  exist in the array help the code skip over missing data, and continue on correctly


    # somehow unlocked / paid media: get download url from media location
         if 'location' in media_info['media']:
            if 'preview' in media_info:
                if 'variants' in media_info['preview']:
                    variants = media_info['media']['variants']
    
                for content in variants:
                    parse_variants(item, content=content, content_type='media', media_info=media_info)
    
     # previews: if media location is not found, we work with the preview media info instead
        if not item.download_url and 'preview' in media_info:
            if 'preview' in media_info:
                if 'variants' in media_info['preview']:
                    variants = media_info['preview']['variants']
    
                for content in variants:
                    parse_variants(item, content=content, content_type='preview', media_info=media_info)
