### ISSUE TITLE
KeyError: 'release_version' in "updater\utils.py"

### ISSUE THREAD

**Issue by elschnorro77** [prof79/fansly-downloader-ng#21]
## Bug Description
 ERROR | 18:47 || An unexpected error occurred: 'release_version'
Traceback (most recent call last):
  File "fansly_downloader_ng.py", line 186, in <module>
  File "fansly_downloader_ng.py", line 103, in main
  File "updater\__init__.py", line 23, in self_update
  File "updater\utils.py", line 274, in check_for_update
  File "updater\utils.py", line 105, in perform_update
KeyError: 'release_version'

## Environment Information
 - Operating System: Windows
 - Fansly Downloader Version: v0.8.9
 - Fansly Downloader Type: Executable, python version

**Comment by prof79** [comment]
Thanks, I've fixed it from 0.8.11 onwards - but I had to disable auto-updating in 0.8.15, it will only print an info message. Adding update logic to update a currently running process is to cumbersome/complicated right now. Should you see odd behavior from 0.8.15+, please tell.
