### ISSUE TITLE
Error 401

### ISSUE THREAD

**Issue by Hotpocketdeath** [prof79/fansly-downloader-ng#50]
I've been having issues with the original downloader, so I tried using this downloader-ng and it's even worse.

The original downloader would only download images, but not videos.  Kept getting errors.  But after setting up NG, this is what I'm getting.

>  ERROR | 13:27 || An unexpected error occurred: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
> Traceback (most recent call last):
>   File "api\fansly.py", line 352, in setup_session
>   File "api\fansly.py", line 508, in get_json_response_contents
>   File "api\fansly.py", line 489, in validate_json_response
>   File "requests\models.py", line 1021, in raise_for_status
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "fansly_downloader_ng.py", line 198, in <module>
>   File "fansly_downloader_ng.py", line 118, in main
>   File "config\fanslyconfig.py", line 106, in get_api
>   File "api\fansly.py", line 59, in __init__
>   File "api\fansly.py", line 359, in setup_session
> RuntimeError: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

Says unauthorized, but I've been logged into fansly with no issues and can view videos just fine.  So I don't know why this error is occurring.

**Comment by dingbat371** [comment]
same issue here.   Original downloader works, but not for videos, this one fails almost immediately with the 401 error above.   Thanks

**Comment by prof79** [comment]
Please see #34 . Fansly have stepped up their game and dislike users using this software. I'm pretty sure something isn't configured properly and the browser autoconfig may be broken, didn't test recently.
