### ISSUE TITLE
I'm new to this

### ISSUE THREAD

**Issue by p0n3swag** [prof79/fansly-downloader-ng#51]
## Bug Description
Tried to get it to Download new content

## Actual behavior
Got this message 
 ERROR | 21:08 || An unexpected error occurred: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
Traceback (most recent call last):
  File "api\fansly.py", line 352, in setup_session
  File "api\fansly.py", line 508, in get_json_response_contents
  File "api\fansly.py", line 489, in validate_json_response
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fansly_downloader_ng.py", line 198, in <module>
  File "fansly_downloader_ng.py", line 108, in main
  File "config\validation.py", line 450, in validate_adjust_config
  File "config\validation.py", line 178, in validate_adjust_token
  File "config\fanslyconfig.py", line 106, in get_api
  File "api\fansly.py", line 59, in __init__
  File "api\fansly.py", line 359, in setup_session
RuntimeError: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

## Environment Information
 - Operating System: Windows
 - Fansly Downloader Version: .97
 - Fansly Downloader Type: Executable
 - Specific creators name: nananightray

**Comment by jake1246** [comment]
Hi friend, I'm a total noob to this as well, and I was getting the exact same error message as you.  I got past it, but this may or may not be helpful for you:

In the "config" file, there are two values you need to fill in:  "authorization token," and "user_agent."  I've previously been using an [older version](https://github.com/Avnsx/fansly-downloader#-quick-start) of this app, which automatically takes you through an intial startup process to populate those two values.  So I just opened the "config" file from the other app, and copied those same two values over to the new "config" file.

I don't know if this newer app was also supposed to run through the initial startup process?  Not sure how else you would get those two values.

Best of luck!

**Comment by 1gintonic** [comment]
check the [wiki](https://github.com/prof79/fansly-downloader-ng/wiki) - it has a starter guide for a manual setup as well :)
