### ISSUE TITLE
Error 500 on the API

### ISSUE THREAD

**Issue by MikesSpicy** [prof79/fansly-downloader-ng#56]
**IMPORTANT:** Be sure to replace all ``{{`` template sections ``⚠️}}`` or your issue may be discarded.

## Bug Description
Trying to download content and getting a "new" error

 ERROR | 16:43 || An unexpected error occurred: Error during session setup: 500 Server Error: Internal Server Error for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
Traceback (most recent call last):
  File "api\fansly.py", line 352, in setup_session
  File "api\fansly.py", line 508, in get_json_response_contents
  File "api\fansly.py", line 489, in validate_json_response
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

## Expected behavior
For it to start downloading

## Actual behavior
Errors out

*If applicable, add screenshots (just paste/`CTRL+V` - or see [this guide](https://stackoverflow.com/a/14494775/15163882)) to help explain your problem.*

## Environment Information
 - Operating System: {{e.g. Windows, Linux, macOS ⚠️}}
 - Fansly Downloader Version: {{e.g. v0.4 ⚠️}}
 - Fansly Downloader Type: {{e.g. Executable, python version ⚠️}}
 - Specific creators name: {{e.g. FanslyModelName ⚠️}}

## User Research
*( fill ``[ ]`` with ``x``, if you've already done said task )*

I have done the following:
- [ ] Looked through [old GitHub issues](https://github.com/prof79/fansly-downloader-ng/issues?&q=is%3Aissue)
- [ ] Read the [config.ini options](https://github.com/prof79/fansly-downloader-ng/wiki/Fansly-Downloader-NG-Settings#explanation-of-configini)
- [ ] Searched the Web (like [DuckDuckGo](https://duckduckgo.com))

## Additional context
I did verify my key is correct but the 500 leads me believe the server knows somethings. up. New Countermeasure?

**Comment by 1gintonic** [comment]
have you updated your token and user-agent?
