### ISSUE TITLE
[Replace with descriptive keypoint title]

### ISSUE THREAD

**Issue by IBananaShake** [prof79/fansly-downloader-ng#57]
## Bug Description
I get an error reading "Missing items 728 (This may indicate a problem)
Comment: the 728 is obviously dependant on the creator I'm trying to download from

## Expected behavior
I kinda hoped it would download everything

## Actual behavior
Downloads some, but not everything

## Environment Information
Windows 10 newest release

Thanks in advance : )

**Comment by IBananaShake** [comment]
Edit: I'm using the .exe version of the downloader

**Comment by IBananaShake** [comment]
Any update regarding this please?

**Comment by 1gintonic** [comment]
here are couple of question that might help to fix your problem for the devs:
1. are you using the timeline download mode?
2. have you tried downloading single posts from this creator?
3. does that work?
4. are you downloading previews?
5. are you using a duplicate threshold?
6. are you downloading this creator in isolation?

the more information the better

**Comment by IBananaShake** [comment]
Greetings and good evening.

1: 
I am using the "normal" download mode

2/3: 
I am now using the latest v0.9.9 version, and when I change the config file from "Normal" to "Single" I get this error message:
` ERROR | 21:35 || An unexpected error occurred: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
Traceback (most recent call last):
  File "api\fansly.py", line 352, in setup_session
  File "api\fansly.py", line 508, in get_json_response_contents
  File "api\fansly.py", line 489, in validate_json_response
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fansly_downloader_ng.py", line 199, in <module>
  File "fansly_downloader_ng.py", line 119, in main
  File "config\fanslyconfig.py", line 106, in get_api
  File "api\fansly.py", line 59, in __init__
  File "api\fansly.py", line 359, in setup_session
RuntimeError: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true`

4:
I am downloading previews

5:
I am using the duplicate threshold feature

6:
I am getting this error with more than one creator on the platform

I have other means of getting their timeline content, it is the message content that I am more worried about not being able to download

**Comment by IBananaShake** [comment]
This error, or a very similar looking error also happens when I try a normal download with the latest version.

My config file contains this text:
`[Options]
download_mode = Normal
show_downloads = True
download_media_previews = True
open_folder_when_finished = True
download_directory = D:\temp\Fansly Downloader
separate_messages = True
separate_previews = False
separate_timeline = True
metadata_handling = Advanced
show_skipped_downloads = True
use_duplicate_threshold = True
use_folder_suffix = True
interactive = True
prompt_on_exit = True
timeline_retries = 10
timeline_delay_seconds = 60`

**Comment by IBananaShake** [comment]
No news?

**Comment by 1gintonic** [comment]
seeing that you get the HTTP Exception 401 Client Error: Unauthorized, seems that you're not using an updated token/check_key - try clearing your browser cache and repeating this step with the manual setup steps recommended in the [wiki](https://github.com/prof79/fansly-downloader-ng/wiki).

**Comment by 1gintonic** [comment]
also you are facing a similar issue like many others (with the newest version) due to a missing dependency in the .exe version :( during the build it went missing and now requires a workaround until @prof79 will update the version.

**Comment by StupidLlamas** [comment]
> No news?

Have you tried changing "use_duplicate_threshold" to False. That worked for me. This is for the Missing Items issue.
