### ISSUE TITLE
Libstdc++ Error

### ISSUE THREAD

**Issue by NextGenRyo** [prof79/fansly-downloader-ng#72]
## Bug Description
No Idea how to describe this but what is this error all about. ""/usr/bin/ffmpeg: /tmp/_MEIwRLL40/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libSPIRV-Tools-opt.so)"

## Expected behavior
Dowload All videos perfectly when starting.

## Actual behavior
Outputs this error when downloading newer videos. Older videos seem to download fine. No idea what the difference is.

![Screenshot_20240621_030032](https://github.com/prof79/fansly-downloader-ng/assets/5172236/fd668972-b904-42dd-8ca5-a8ae8ec3f379)

## Environment Information
 - Operating System: Arch Linux
 - Fansly Downloader Version: v0.9.7
 - Fansly Downloader Type: Python Version
 - Specific creators name: Kflexible

## User Research
Don't Know what this means exactly

I have done the following:
I've looked through old issues
I've read the config
I've also search the web.

## Additional context
I should note that i've never used this program before. This is the only version i've used. Does is have somethig to do with ffmpeg? I also have libstdc++ installed with GlibCXX_3.4.30 library. This is in user/local i think. This program is a little confusing to use for people who dont use python often maybe consider more detail instalation for linux or mac users. Also I should noye that ALL images donwload with absolutly no issues.

**Comment by tdp4** [comment]
This is an issue with whatever this app is putting in `/tmp/_MEIwRLL40/`.  I can't find why libs go in there unless it is packaged with the release.  Either case, its is aging out and newer linux cannot have the old versions of GCLIB that the packaged `libstdc++.so.6` needs.

**Comment by tdp4** [comment]
I have verified the the packaged linux release (binary) for the current version (v0.9.9) gives the error on Ubuntu 23.10, but the python version does not.

Binary:
```
 Info | 22:49 || Downloading video '2024-06-30_at_09-29_preview_id_663789636048400384.m3u8'
 WARNING | 22:49 || Skipping invalid item: Error running ffmpeg - exit code 1: /usr/bin/ffmpeg: /tmp/_MEIDPo5J6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libavfilter.so.9)
/usr/bin/ffmpeg: /tmp/_MEIDPo5J6/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libavfilter.so.9)
/usr/bin/ffmpeg: /tmp/_MEIDPo5J6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/librubberband.so.2)
```

Python:
```
 Info | 23:06 || Downloading video '2024-06-30_at_09-29_preview_id_663789636048400384.m3u8'
 Info | 23:07 || Downloading video '2024-06-26_at_10-20_id_662352980825088000.m3u8'
 Info | 23:07 || Downloading video '2024-06-05_at_08-21_preview_id_654712771316817920.m3u8'
 Info | 23:07 || Deduplication [Media ID]: image '2024-06-05_at_08-20_preview_id_654712759195279361.jpeg' → skipped
 Info | 23:07 || Downloading image '2024-06-05_at_08-20_preview_id_654712747807744000.jpeg'
 Info | 23:07 || Downloading image '2024-06-05_at_08-20_preview_id_654712742850080768.jpeg'
 Info | 23:07 || Downloading image '2024-06-05_at_07-43_id_654703270446505984.jpeg'
 Info | 23:07 || Downloading image '2024-06-05_at_07-43_id_654703269720891392.jpeg'
 ```
 
 Please verify your build environment for binaries can work on a current linux versions or state a requirement if its not fixable currently.
 
 Otherwise, a valid work-a-round is to just use the python version.   Maybe someone can write up how to use virtual environments in python to keep things tidy.

**Comment by ZOMGsheikh** [comment]
> I have verified the the packaged linux release (binary) for the current version (v0.9.9) gives the error on Ubuntu 23.10, but the python version does not.
> 
> Binary:
> 
> ```
>  Info | 22:49 || Downloading video '2024-06-30_at_09-29_preview_id_663789636048400384.m3u8'
>  WARNING | 22:49 || Skipping invalid item: Error running ffmpeg - exit code 1: /usr/bin/ffmpeg: /tmp/_MEIDPo5J6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/libavfilter.so.9)
> /usr/bin/ffmpeg: /tmp/_MEIDPo5J6/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libavfilter.so.9)
> /usr/bin/ffmpeg: /tmp/_MEIDPo5J6/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /lib/x86_64-linux-gnu/librubberband.so.2)
> ```
> 
> Python:
> 
> ```
>  Info | 23:06 || Downloading video '2024-06-30_at_09-29_preview_id_663789636048400384.m3u8'
>  Info | 23:07 || Downloading video '2024-06-26_at_10-20_id_662352980825088000.m3u8'
>  Info | 23:07 || Downloading video '2024-06-05_at_08-21_preview_id_654712771316817920.m3u8'
>  Info | 23:07 || Deduplication [Media ID]: image '2024-06-05_at_08-20_preview_id_654712759195279361.jpeg' → skipped
>  Info | 23:07 || Downloading image '2024-06-05_at_08-20_preview_id_654712747807744000.jpeg'
>  Info | 23:07 || Downloading image '2024-06-05_at_08-20_preview_id_654712742850080768.jpeg'
>  Info | 23:07 || Downloading image '2024-06-05_at_07-43_id_654703270446505984.jpeg'
>  Info | 23:07 || Downloading image '2024-06-05_at_07-43_id_654703269720891392.jpeg'
> ```
> 
> Please verify your build environment for binaries can work on a current linux versions or state a requirement if its not fixable currently.
> 
> Otherwise, a valid work-a-round is to just use the python version. Maybe someone can write up how to use virtual environments in python to keep things tidy.

When using the python version in Fedora, i get this error: 

`Traceback (most recent call last):
  File "/home/umrn/fansly-downloader-ng/fansly-downloader-ng-0.9.7/fansly_downloader_ng.py", line 36, in <module>
    from config import FanslyConfig, load_config, validate_adjust_config
  File "/home/umrn/fansly-downloader-ng/fansly-downloader-ng-0.9.7/config/__init__.py", line 4, in <module>
    from .config import copy_old_config_values, load_config
  File "/home/umrn/fansly-downloader-ng/fansly-downloader-ng-0.9.7/config/config.py", line 12, in <module>
    from config.fanslyconfig import FanslyConfig
  File "/home/umrn/fansly-downloader-ng/fansly-downloader-ng-0.9.7/config/fanslyconfig.py", line 9, in <module>
    from config.modes import DownloadMode
  File "/home/umrn/fansly-downloader-ng/fansly-downloader-ng-0.9.7/config/modes.py", line 3, in <module>
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'
`

Whereas the binary is ok, but then it is having those 'GLIBCXX' errors and not downloading any videos, any idea how to i work with the python version?

**Comment by 1gintonic** [comment]
[here](https://github.com/prof79/fansly-downloader-ng/issues/80#issuecomment-2249261123)'s a guide on virtual python environments provided by @recolier
