### ISSUE TITLE
[43]ERROR unexpected error during Timeline download

### ISSUE THREAD

**Issue by catnip-stack** [prof79/fansly-downloader-ng#76]
getting this error:

[43]ERROR | 11:43 || Unexpected error during Timeline download:
Traceback (most recent call last):
  File "download\common.py", line 151, in process_download_accessible_media
  File "download\media.py", line 202, in download_media
  File "fileio\dedupe.py", line 74, in dedupe_media_file
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

no clue what it means or how to fix. 
running on w11

**Comment by Isbbrt** [comment]
The same here. Download some files and then crash. It would be interesting if it showed which media link is downloading so, in case of error, we can download it individually. I would also like to know what this "Timeline cursor:", "CID:" and these media ID numbers that come before the file extension are. Thanks
I'm on version 0.9.9

**Comment by pakkalin** [comment]
for me also the same error

**Comment by Mikemc20** [comment]
I kind of figured this one out by accident while trying to get the python version to work but it seems like the creator left out some dependency's when putting it together (in this case it would be: 'scipy.special._special_ufuncs'.) I had to basically try and run it over and over to find most of them, and then i had to download them all individually. I will just note here that my solution probably wont work with the executable version.

**Comment by 1gintonic** [comment]
try using the python version, that one works :) I think @prof79 forgot to add the dependency when building the executable like @Mikemc20 mentioned :/

**Comment by Animalm4st3r** [comment]
I just ran the 0.9.7 windows version, wich does not produce this error and downloads everything
