### ISSUE TITLE
Traceback error on windows

### ISSUE THREAD

**Issue by Teufel0406** [prof79/fansly-downloader-ng#78]
[ [43]ERROR ] [2024-06-30 | 19:44]: Unexpected error during Messages download: 
Traceback (most recent call last):
  File "download\common.py", line 151, in process_download_accessible_media
  File "download\media.py", line 202, in download_media
  File "fileio\dedupe.py", line 74, in dedupe_media_file
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

**Comment by 7evenlxrd** [comment]
Use python version. Works for me

**Comment by 1gintonic** [comment]
try using the python version, that one works :) I think @prof79 forgot to add the dependency when building the executable :/
