### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by IBananaShake** [prof79/fansly-downloader-ng#87]
I'm getting a "Module Not Found Error" running the latest 9.9 downloader

[ [43]ERROR ] [2024-07-19 | 23:56]: Unexpected error during Messages download: 
Traceback (most recent call last):
  File "download\common.py", line 151, in process_download_accessible_media
  File "download\media.py", line 202, in download_media
  File "fileio\dedupe.py", line 74, in dedupe_media_file
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

How do I resolve this issue?
The old 4.1 downloader works, just not for the .m328 or whatever video's are not downloaded

**Comment by IBananaShake** [comment]
Windows 10, I have all of the updates for the OS

**Comment by shapman88** [comment]
I'm having the same error on v0.9.9 on Windows 11.

**Comment by BunBunZeroOne** [comment]
now we play the waiting game. For all the smart people to solve the problem.

**Comment by 1gintonic** [comment]
try using the python version, that one works :) I think @prof79 forgot to add the dependency when building the executable :/ there's a step-by-step guide provided by @recolier [here](https://github.com/prof79/fansly-downloader-ng/issues/80#issuecomment-2249261123) on how to set up a python environment.
Alternatively, try adding `scipy==1.14.0` to the requirements.txt and then rebuilt the exe using the build.ps1 script - this should fix the dependency issue.

**Comment by Mantra2222** [comment]
> try using the python version, that one works :) I think @prof79 forgot to add the dependency when building the executable :/ there's a step-by-step guide provided by @recolier [here](https://github.com/prof79/fansly-downloader-ng/issues/80#issuecomment-2249261123) on how to set up a python environment. Alternatively, try adding `scipy==1.14.0` to the requirements.txt and then rebuilt the exe using the build.ps1 script - this should fix the dependency issue.

How does one "rebuilt the exe using the build.ps1 script"? Also the step-by-step guide provided by @recolier [here](https://github.com/prof79/fansly-downloader-ng/issues/80#issuecomment-2249261123) on how to set up a python environment  is down and inaccessible.

**Comment by palmerbomber1** [comment]
> > try using the python version, that one works :) I think @prof79 forgot to add the dependency when building the executable :/ there's a step-by-step guide provided by @recolier [here](https://github.com/prof79/fansly-downloader-ng/issues/80#issuecomment-2249261123) on how to set up a python environment. Alternatively, try adding `scipy==1.14.0` to the requirements.txt and then rebuilt the exe using the build.ps1 script - this should fix the dependency issue.
> 
> How does one "rebuilt the exe using the build.ps1 script"? Also the step-by-step guide provided by @recolier [here](https://github.com/prof79/fansly-downloader-ng/issues/80#issuecomment-2249261123) on how to set up a python environment is down and inaccessible.

Wayback machine crawled that link, [heres](http://web.archive.org/web/20241001085407/https://github.com/prof79/fansly-downloader-ng/issues/80) the quick URL to it 

Being as he only has one comment on that mysteriously missing page, here it is in text just in case wayback gets DDOSed again (note Im just copy and pasting, hopefully its legible and links work)

> Recoiler 
Worked with Python 3.10.11. Might work with another Python 3 version.
Hopefully bulletproof instructions for Windows:

    [Download the source code from latest release](http://web.archive.org/web/20241001085407/https://github.com/prof79/fansly-downloader-ng/releases)
    a. Extract somewhere, remember this directory, I'll refer to it as YOUR_FANSLY_DL_DIR. I recommend to put it where your executable file is.
    [Open up command prompt or Powershell](http://web.archive.org/web/20241001085407/https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/starting-windows-powershell?view=powershell-7.4), Run the following command and replace with your directory.

    cd YOUR_FANSLY_DL_DIR

    [Create a virtual environment](http://web.archive.org/web/20241001085407/https://docs.python.org/3/library/venv.html). You should now see a prefix (.venv) in your terminal.
    a. If Python 3.10 is your only/default python (can check with python -V)

    python -m pip install virtualenv
    python -m venv .venv
    .\.venv\Scripts\activate

    b. Otherwise:

    py -3.10 -m pip install virtualenv
    py -3.10 -m venv .venv
    .\.venv\Scripts\activate

    c. If you get an error at the first line for both saying something doesn't exist, if you're not tech savvy, reinstall Python and make sure to select the option to add to PATH.
    Install requirements.

    python -m pip install -r requirements.txt

    Run the thing

    python fansly_downloader_ng.py
