### ISSUE TITLE
Downloading Timeline and Get this Error. 

### ISSUE THREAD

**Issue by Phtephent** [prof79/fansly-downloader-ng#92]
I'm trying to download pictures from the creators timeline, but I get this error all the time. I'm able to download one picture at a time but not multiple like I was used to.

Traceback (most recent call last):
  File "download\common.py", line 151, in process_download_accessible_media
    download_media(config, state, accessible_media)
  File "download\media.py", line 202, in download_media
    is_dupe = dedupe_media_file(config, state, media_item.mimetype, file_save_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fileio\dedupe.py", line 74, in dedupe_media_file
    file_hash = get_hash_for_image(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "fileio\fnmanip.py", line 71, in get_hash_for_image
    file_hash = str(imagehash.phash(img, hash_size = 16))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "imagehash\__init__.py", line 272, in phash
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\__init__.py", line 93, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fftpack\_basic.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\__init__.py", line 91, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\fft\_fftlog_backend.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 807, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

**Comment by CaptainKoons** [comment]
I have the same issue:

> [43]ERROR | 09:21 || Unexpected error during Timeline download:
> Traceback (most recent call last):
>   File "download\common.py", line 151, in process_download_accessible_media
>   File "download\media.py", line 202, in download_media
>   File "fileio\dedupe.py", line 74, in dedupe_media_file
>   File "fileio\fnmanip.py", line 71, in get_hash_for_image
>   File "imagehash\__init__.py", line 272, in phash
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "scipy\fftpack\__init__.py", line 93, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "scipy\fftpack\_basic.py", line 8, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "scipy\fft\__init__.py", line 91, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "scipy\fft\_fftlog.py", line 10, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "scipy\fft\_fftlog_backend.py", line 4, in <module>
>   File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
>   File "scipy\special\__init__.py", line 807, in <module>
>   File "scipy\\special\\_ufuncs.pyx", line 17294, in init scipy.special._ufuncs
> ModuleNotFoundError: No module named 'scipy.special._special_ufuncs'

It seems to only popup with pictures (no issues with videos)

Thanks in advance!
CK

**Comment by firedbeab** [comment]
me too
i asked ChatGPT and it told me there's something wrong with the duplicate check option.
But it still occurs after I change the option to False.
And also, I checked my local python base environment, I've already installed the scipy pack (ver. 1.13.1)
I'll try to reinstall the latest version. If it works, I'll come back.

**Comment by firedbeab** [comment]
Unfortunately, it didn't work :(
I updated the scipy to 1.15.2
I have no idea how to solve this, sad

**Comment by firedbeab** [comment]
OK guys I found the solution... Finally.
Use the version 0.97 and everything goes well
I don't know why the upper version has this kind of issue.
Whatever, I'll stick on using 0.97
