### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by ChaosMatt** [prof79/fansly-downloader-ng#97]
ERROR | 01:53 || An unexpected error occurred: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
Traceback (most recent call last):
  File "api\fansly.py", line 352, in setup_session
  File "api\fansly.py", line 508, in get_json_response_contents
  File "api\fansly.py", line 489, in validate_json_response
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fansly_downloader_ng.py", line 199, in <module>
  File "fansly_downloader_ng.py", line 109, in main
  File "config\validation.py", line 484, in validate_adjust_config
  File "config\validation.py", line 179, in validate_adjust_token
  File "config\fanslyconfig.py", line 106, in get_api
  File "api\fansly.py", line 59, in __init__
  File "api\fansly.py", line 359, in setup_session
RuntimeError: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

**Comment by makurei** [comment]
I get this same error

 WARNING | 18:12 || Authorization token '' is unmodified, missing or malformed
                    in the configuration file.
 Config | 18:12 || Trying to automatically configure Fansly authorization token
                   from any browser storage available on the local system ...
 Config | 18:12 || Chrome browser is open but it needs to be closed for automatic configurator
                   to search your Fansly account in the browser's storage.
                   Please save any important work within the browser & close the browser yourself
                   or it will be closed automatically after continuing.

                   ► Press <ENTER> to continue!
 Config | 18:12 || Successfully closed Chrome browser.

 ERROR | 18:12 || An unexpected error occurred: Token or user agent error creating Fansly API object.
Traceback (most recent call last):
  File "fansly_downloader_ng.py", line 199, in <module>
  File "fansly_downloader_ng.py", line 109, in main
  File "config\validation.py", line 484, in validate_adjust_config
  File "config\validation.py", line 179, in validate_adjust_token
  File "config\fanslyconfig.py", line 120, in get_api
RuntimeError: Token or user agent error creating Fansly API object.

**Comment by makurei** [comment]
It was perfect before, now its not working :(

**Comment by jakob4800** [comment]
Same here

ERROR | 04:52 || An unexpected error occurred: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
Traceback (most recent call last):
  File "api\fansly.py", line 352, in setup_session
  File "api\fansly.py", line 508, in get_json_response_contents
  File "api\fansly.py", line 489, in validate_json_response
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fansly_downloader_ng.py", line 199, in <module>
  File "fansly_downloader_ng.py", line 109, in main
  File "config\validation.py", line 484, in validate_adjust_config
  File "config\validation.py", line 179, in validate_adjust_token
  File "config\fanslyconfig.py", line 106, in get_api
  File "api\fansly.py", line 59, in __init__
  File "api\fansly.py", line 359, in setup_session
RuntimeError: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

**Comment by palmerbomber1** [comment]
chaosmatt and jakob4800, clicking on the urls from your messages it shows 
`{"success":false,"error":{"code":99,"details":"missing parameter \"sessionToken\""}}`
I wonder if the issue is with your authorization_token ?

**Comment by palmerbomber1** [comment]
makurei you have the error `WARNING | 18:12 || Authorization token '' is unmodified, missing or malformed
in the configuration file.` It looks like you didnt set your authorization_token, or missed a few characters of it when you copied it

**Comment by jakob4800** [comment]
> chaosmatt and jakob4800, clicking on the urls from your messages it shows `{"success":false,"error":{"code":99,"details":"missing parameter \"sessionToken\""}}` I wonder if the issue is with your authorization_token ?

It could be, How would i resolve it or change the token?

**Comment by palmerbomber1** [comment]
> It could be, How would i resolve it or change the token?

The manual steps for setting the token are [here](https://github.com/prof79/fansly-downloader-ng/wiki/Getting-Started)

**Comment by makurei** [comment]
I think this is looking for a check_key

Info | 10:44 || Check Key:

 ERROR | 10:44 || An unexpected error occurred: Token or user agent error creating Fansly API object.
Traceback (most recent call last):
  File "fansly_downloader_ng.py", line 199, in <module>
  File "fansly_downloader_ng.py", line 119, in main
  File "config\fanslyconfig.py", line 120, in get_api
RuntimeError: Token or user agent error creating Fansly API object.

**Comment by maraudersmapx** [comment]
> The manual steps for setting the token are [here](https://github.com/prof79/fansly-downloader-ng/wiki/Getting-Started)

Just reporting that I am also experiencing this issue. Will follow the manual steps.
