### ISSUE TITLE
[Replace with descriptive keypoint title]

### ISSUE THREAD

**Issue by TimN0001** [prof79/fansly-downloader-ng#99]
**IMPORTANT:** Be sure to replace all ``{{`` template sections ``}}`` or your issue may be discarded.

## Bug Description
{{ I'm trying to run the python version with all the modules installed and am getting an error in web.py. Im running windows 11. 

Successfully installed ImageHash-4.3.1 PyWavelets-1.6.0 backports-datetime-fromisoformat-2.0.2 loguru-0.7.2 m3u8-4.0.0 markdown-it-py-3.0.0 mdurl-0.1.2 memory-profiler-0.61.0 pillow-10.2.0 plyvel-ci-1.5.0 psutil-5.9.8 pyffmpeg-2.4.2.18.1 pygments-2.18.0 python-dateutil-2.8.2 requests-2.31.0 rich-13.7.0 scipy-1.13.1 six-1.16.0 websockets-12.0 win32-setctime-1.1.0

C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9>python3.exe fansly_downloader_ng.py
Traceback (most recent call last):
  File "C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9\fansly_downloader_ng.py", line 37, in <module>
    from config import FanslyConfig, load_config, validate_adjust_config
  File "C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9\config\__init__.py", line 4, in <module>
    from .config import copy_old_config_values, load_config
  File "C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9\config\config.py", line 12, in <module>
    from config.fanslyconfig import FanslyConfig
  File "C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9\config\fanslyconfig.py", line 12, in <module>
    from api import FanslyApi
  File "C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9\api\__init__.py", line 4, in <module>
    from .fansly import FanslyApi
  File "C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9\api\fansly.py", line 18, in <module>
    from utils.web import get_flat_qs_dict, split_url
  File "C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9\utils\web.py", line 263, in <module>
    def get_release_info_from_github(current_program_version: str) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

C:\Users\timne\Downloads\fansly-downloader-ng-0.9.9>

 }}

## Expected behavior
{{ The exe has different behavior I exptected it to look at the config file and start downloading.}}

## Actual behavior
{{ What actually happened? It crashed }}

*If applicable, add screenshots (just paste/`CTRL+V` - or see [this guide](https://stackoverflow.com/a/14494775/15163882)) to help explain your problem.*

## Environment Information
 - Operating System: {{e.g. Windows,}}
 - Fansly Downloader Version: {{e.g. v0.9.9}}
 - Fansly Downloader Type: {{e.g python version}}
 - Specific creators name: {{e.g. ccflight}}

## User Research
*( fill ``[]`` with ``x``, if you've already done said task )*

I have done the following:
- [x] Looked through [old GitHub issues](https://github.com/prof79/fansly-downloader-ng/issues?&q=is%3Aissue)
- [x] Read the [config.ini options](https://github.com/prof79/fansly-downloader-ng/wiki/Fansly-Downloader-NG-Settings#explanation-of-configini)
- [x] Searched the Web (like [DuckDuckGo](https://duckduckgo.com))

## Additional context
{{Add any other context about the problem here. I usually run the exe version but since there was some python changes needed in the latest release I made the change to api/fansly.py and  download/messages.py to fix the issue of images not downloading }}

**Comment by TimN0001** [comment]
Python needed to be updated that solved this issue.
